### ISSUE TITLE
works GREAT but why redirects to google sheet ?

### ISSUE THREAD

**Issue by msabryamin** [cybercase/google-forms-html-exporter#1]
hello ,, which jquery forms do you use ? and is there any way to stop redirect to google thanks form ??

**Comment by cybercase** [comment]
Hello @msa138 
I'm using jquery-form (https://github.com/jquery-form/form) version 4.2.1, but I guess that any version greater than this should work.

Actually, redirection to Google Form should be blocked by the generated JS script (after the generated HTML).
Could you check that you've loaded the JS script correctly in your page?

**Comment by msabryamin** [comment]
well , i guess there was an error in javascript (no conflict) in wordpress  .. sorry for that :) .. it works great :+1:
