### ISSUE TITLE
Response issue

### ISSUE THREAD

**Issue by wira-sandy** [cybercase/google-forms-html-exporter#2]
The form submitted and it says 1 response. But the contents are blank.

**Comment by cybercase** [comment]
Hello @wira-sandy, could you send me the link of the form you're using so that I can try to reproduce the issue?

**Comment by wira-sandy** [comment]
Thanks @cybercase for replying :)
Here are the google form that I'm trying to test : [link](https://docs.google.com/forms/d/e/1FAIpQLSf3Qx4cZVKm39UOSItlDo7RrZ9bHEzkwNKFYYWyDJCDem35Gg/viewform)

And here is the spreadsheet for the response : [link](https://docs.google.com/spreadsheets/d/1U-ksTkfOJiU9nKxEgGfhYrFUeK7PdpvFRCpKEbH3x38/edit?usp=drivesdk)

**Comment by cybercase** [comment]
@wira-sandy I've made some changes to the exporter... could you test if now it's working fine?

**Comment by wira-sandy** [comment]
@cybercase thanks I'll see and tell u afterward. Thanks for help

**Comment by wira-sandy** [comment]
@cybercase it works like a magic. Thanks!
