### ISSUE TITLE
Issue with google form which require sign-in

### ISSUE THREAD

**Issue by wira-sandy** [cybercase/google-forms-html-exporter#3]
There are issue with form which require user to sign-in to google. The response not recorded.
I manage to get the sign-in process from my web. But the form cant be recorded to spreadsheet.

**Comment by cybercase** [comment]
@wira-sandy thanks for reporting. I'll try to check how forms which require google sign-in work and see if it can be fixed. I'll try to work on this during next weekend 🤞

**Comment by wira-sandy** [comment]
Glad to hear that :) thanks

**Comment by cybercase** [comment]
@wira-sandy I've made some changes to allow the google authentication cookies over the submit form request. This should make the form works fine for authenticated users.

**Comment by wira-sandy** [comment]
Thanks!
