### ISSUE TITLE
Is there any way to copy the css and the style automatically?

### ISSUE THREAD

**Issue by guilhermecgs** [cybercase/google-forms-html-exporter#4]

**Comment by cybercase** [comment]
Hello @guilhermecgs. If you mean to copy the Google form's style I'm afraid it's out of the scope of this tool. The best solution is to use Google Forms Exporter to get the html and style the result with a library like http://materializecss.com/ or https://getmdl.io/

**Comment by guilhermecgs** [comment]
ok, thanks!
