### ISSUE TITLE
Redirect to a custom Thank you page

### ISSUE THREAD

**Issue by GarfieldS** [cybercase/google-forms-html-exporter#5]
Can you provide an example of the code that actually redirects to a custom thank you page? 

As simple as it may be I was not able to get this to work and maybe I am not taking something into account or perhaps you may not be taking something into account but if there were a working example it would be clear what the adjustment in the code would need to look like to make this possible. 

Now, I am just simply befuddled after several trial variations in the code and no clear direction and lost.

**Comment by GarfieldS** [comment]
I found a workaround solution but still interested in any clarification on how to deal with redirecting on form submit.

**Comment by cybercase** [comment]
Hello @GarfieldS 
After exporting your Google Form, the exported javascript should contain this snippet of code:

```javascript
    $('#bootstrapForm').ajaxSubmit({
        data: extraData,
        dataType: 'jsonp',  // This won't really work. It's just to use a GET instead of a POST to allow cookies from different domain.
        error: function () {
            // Submit of form should be successful but JSONP callback will fail because Google Forms
            // does not support it, so this is handled as a failure.
            alert('Form Submitted. Thanks.')
            // You can also redirect the user to a custom thank-you page:
            // window.location = 'http://www.mydomain.com/thankyoupage.html'
        }
    })
```

To redirect the user to your custom thankyou page (let's say you've already built a thankyou page at `http://www.mysite.com/thankyoupage`), you need to change the code like the following:

```javascript
    $('#bootstrapForm').ajaxSubmit({
        data: extraData,
        dataType: 'jsonp',  // This won't really work. It's just to use a GET instead of a POST to allow cookies from different domain.
        error: function () {
            // Redirect the user to the thankyou page
            window.location = 'http://www.mysite.com/thankyoupage'
        }
    })
```

This will make the browser go to `http://www.mysite.com/thankyoupage` just after the submission of the form.

Hope this helps

**Comment by GarfieldS** [comment]
Thank you very much!

The code that usually comes out looks like this: (code from the demo) 
<pre>
$('#bootstrapForm').submit(function (event) {
    event.preventDefault()
    var extraData = {}
    $('#bootstrapForm').ajaxSubmit({
        data: extraData,
        dataType: 'jsonp',  // This won't really work. It's just to use a GET instead of a POST to allow cookies from different domain.
        error: function () {
            // Submit of form should be successful but JSONP callback will fail because Google Forms
            // does not support it, so this is handled as a failure.
            alert('Form Submitted. Thanks.')
            // You can also redirect the user to a custom thank-you page:
            // window.location = 'http://www.mydomain.com/thankyoupage.html'
        }
    })
})
</pre>

There is a double mention of bootstrapform so this may have made things a little confusing.
