### ISSUE TITLE
How we can use it with the new upload option 

### ISSUE THREAD

**Issue by KalipheGTU** [cybercase/google-forms-html-exporter#6]
Hi!
great job!
1-How we can use it with the new upload option?
2-How we can add a Map inside the form with Lat/Long track?
3-how we can embed it on our website? 
Thank you

**Comment by cybercase** [comment]
Hello @KalipheGTU,
1. unfortunately the upload option is still not supported. I'm currently having a look at how it works to see if I can do something, but it will take some time.
2. You can add or change the exported HTML as you like. One way to add a map to an html page is to embed a google maps into an iframe. Here's where you can start: https://developers.google.com/maps/documentation/embed/start
3. You can just copy&paste the code into one of your website's page. Just don't forget to add the javascript script a the end of the page.

Hope it helps,

Stefano

**Comment by KalipheGTU** [comment]
Thank you for the answer, I will try it.
Cheers

**Comment by Bosco98** [comment]
Hey did you find a way around for file uploads ?

**Comment by cybercase** [comment]
@Bosco98 Unfortunately I didn't :(
